version: "3"

services:
  server:
    build: .
    restart: always
    ports:
      - "8081:8081"
      - "8080:8080"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
