name: Go

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Test Setup
        run: docker pull httpd:latest
      - name: Test
        run: go test -v ./test/... -coverprofile=coverage.out
      - name: report coverage
        uses: k1LoW/octocov-action@v0
